### ISSUE TITLE
Has anyone successfully built on Windows?

### ISSUE THREAD

**Issue by tkzcxl** [kibble-cabal/godot-rive#18]
I got an error after trying to build
`
Traceback (most recent call last):
  File "D:\Godot\Godot_v4.2.2-stable_mono_win64\godot-rive\build\build.py", line 236, in <module>
    build_rive(platform, target)
  File "D:\Godot\Godot_v4.2.2-stable_mono_win64\godot-rive\build\build.py", line 75, in build_rive
    handle_fail(subprocess.call(args, cwd="../thirdparty/rive-cpp"))
  File "C:\Users\a1247\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "C:\Users\a1247\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\a1247\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1421, in _execute_child
    hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
FileNotFoundError: [WinError 2]
Process finished with exit code 1

`

**Comment by Reuzi3** [comment]
Any solution for this on the horizon?
